package com.dreamsoftware.tvnexa.ui.theme

import androidx.compose.ui.unit.dp

object Dimens {

    val HOME_SIDE_MENU_DRAWER_CONTENT_PADDING = 12.dp
    val HOME_SIDE_MENU_CLOSE_DRAWER_WIDTH = 120.dp
    val HOME_SIDE_MENU_OPEN_LOGO_HEIGHT = 80.dp
    val HOME_SIDE_MENU_CLOSE_LOGO_HEIGHT = 40.dp
    val HOME_SIDE_MENU_DRAWER_CONTENT_VERTICAL_ARRANGEMENT = 8.dp
    val HOME_SIDE_MENU_CLOSE_AVATAR_SIZE = 50.dp
    val HOME_SIDE_MENU_OPEN_AVATAR_SIZE = 55.dp
    const val HOME_SIDE_MENU_AVATAR_FOCUSED_SCALE = 1.1f
    val HOME_SIDE_MENU_AVATAR_PADDING = 0.dp

    val SAVE_PROFILE_AVATAR_SIZE = 60.dp
    const val SAVE_PROFILE_AVATAR_FOCUSED_SCALE = 1.2f
    val PROFILE_AVATAR_NO_PADDING = 0.dp
    const val SAVE_PROFILE_AVATAR_SELECTED_FOCUSED_SCALE = 1f
}